/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lancastersguiv2;
import FOHClasses.Booking;
import FOHClasses.Collection.BookingCollection;
import FOHClasses.Collection.OrderCollection;
//import FOHClasses.Order;
import FOHClasses.Notification;
import FOHClasses.Order;
import FOHClasses.Terminal;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

import static lancastersguiv2.BookingTableManager.updateBookingTable;


/**
 *
 * @author josep
 */
public class TabbedGUI extends javax.swing.JFrame {

    DefaultListModel unpaidModel = new DefaultListModel();
    DefaultListModel notificationModel = new DefaultListModel();
    DefaultTableModel ordersModel = new DefaultTableModel();
    String[] notificationList;
    Booking booking;
    /**
     * Creates new form TabbedGUI
     */
    public TabbedGUI() {
        initComponents();


        for (Booking booking : BookingCollection.getAll()) {
            if (!booking.isPaid()) {
                unpaidModel.addElement(booking.getBookingId());
            }
        }

        /*
        String[] sa = {"BookingID", "Cover", "Table", "Items", "Note", "Waiter"};
        ordersModel.addColumn(sa);
        String[] sa2 = {"", "", "", "", "", ""};
        for (Order order : OrderCollection.getAll()) {

        }*/

//        notificationList = Notification.getNotification();
//        for (int i = 0; i < notificationList.length; i++) {
//            notificationModel.addElement(notificationList[i]);
//        }

        listUnpaidOrders.setModel(unpaidModel);
        tOrders.setModel(ordersModel);
//        listNotifications.setModel(notificationModel);



        // Use the utility class to populate the waiter dropdown
        GUIUtils.populateWaiterDropdown(cbNbWaiter);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jButton15 = new javax.swing.JButton();
        tpFOHGUIMain = new javax.swing.JTabbedPane();
        pNotifications = new javax.swing.JPanel();
        spNotifications = new javax.swing.JScrollPane();
        listNotifications = new javax.swing.JList<>();
        bNotificationDelete = new javax.swing.JButton();
        pMenu = new javax.swing.JPanel();
        spMenu = new javax.swing.JScrollPane();
        tMenu = new javax.swing.JTable();
        pBooking = new javax.swing.JPanel();
        pNewBooking = new javax.swing.JPanel();
        tfNbName = new javax.swing.JTextField();
        lNbName = new javax.swing.JLabel();
        lNbPhoneNumber = new javax.swing.JLabel();
        tfNbPhoneNumber = new javax.swing.JTextField();
        lNbNoGuests = new javax.swing.JLabel();
        lNbTime = new javax.swing.JLabel();
        lNbDate = new javax.swing.JLabel();
        bNbSubmit = new javax.swing.JButton();
        lNbTables = new javax.swing.JLabel();
        cbNbDay = new javax.swing.JComboBox<>();
        cbNbMonth = new javax.swing.JComboBox<>();
        cbNbYear = new javax.swing.JComboBox<>();
        cbNbHour = new javax.swing.JComboBox<>();
        cbNbMinute = new javax.swing.JComboBox<>();
        cbNbNoGuests = new javax.swing.JComboBox<>();
        lNbBookingLength = new javax.swing.JLabel();
        cbNbBookingLength = new javax.swing.JComboBox<>();
        tfTables = new javax.swing.JTextField();
        lNbWaiter = new javax.swing.JLabel();
        cbNbWaiter = new javax.swing.JComboBox<>();
        pEditBooking = new javax.swing.JPanel();
        bBookingDelete = new javax.swing.JButton();
        spEditBooking = new javax.swing.JScrollPane();
        tBookings = new javax.swing.JTable();
        cbBookingsSelect = new javax.swing.JComboBox<>();
        bBookingEdit = new javax.swing.JButton();
        pPayment = new javax.swing.JPanel();
        spUnpaidOrders = new javax.swing.JScrollPane();
        listUnpaidOrders = new javax.swing.JList<>();
        lUnpaidOrders = new javax.swing.JLabel();
        bPrintBill = new javax.swing.JButton();
        bSelectBill = new javax.swing.JButton();
        spSelectedBill = new javax.swing.JScrollPane();
        taSelectedBill = new javax.swing.JTextArea();
        lSelectedBill = new javax.swing.JLabel();
        bPayWholeBill = new javax.swing.JButton();
        bPaySplitBill = new javax.swing.JButton();
        pOrder = new javax.swing.JPanel();
        lOrders = new javax.swing.JLabel();
        bOEdit = new javax.swing.JButton();
        bODelete = new javax.swing.JButton();
        bONewOrder = new javax.swing.JButton();
        spOrders = new javax.swing.JScrollPane();
        tOrders = new javax.swing.JTable();
        pTablePlan = new javax.swing.JPanel();
        bTable9 = new javax.swing.JButton();
        bTable13 = new javax.swing.JButton();
        bTable1 = new javax.swing.JButton();
        bTable6 = new javax.swing.JButton();
        bTable15 = new javax.swing.JButton();
        bTable14 = new javax.swing.JButton();
        bTable5 = new javax.swing.JButton();
        bTable2 = new javax.swing.JButton();
        bTable4 = new javax.swing.JButton();
        bTable12 = new javax.swing.JButton();
        bTable8 = new javax.swing.JButton();
        bTable10 = new javax.swing.JButton();
        bTable11 = new javax.swing.JButton();
        bTable3 = new javax.swing.JButton();
        bTable7 = new javax.swing.JButton();
        cbTpDay = new javax.swing.JComboBox<>();
        cbTpYear = new javax.swing.JComboBox<>();
        tbTp1S = new javax.swing.JToggleButton();
        tbTp1M = new javax.swing.JToggleButton();
        tbTp1D = new javax.swing.JToggleButton();
        tbTp2S = new javax.swing.JToggleButton();
        tbTp2M = new javax.swing.JToggleButton();
        tbTp2D = new javax.swing.JToggleButton();
        tbTp3S = new javax.swing.JToggleButton();
        tbTp3M = new javax.swing.JToggleButton();
        tbTp3D = new javax.swing.JToggleButton();
        tbTp4S = new javax.swing.JToggleButton();
        tbTp4M = new javax.swing.JToggleButton();
        tbTp4D = new javax.swing.JToggleButton();
        tbTp5S = new javax.swing.JToggleButton();
        tbTp5M = new javax.swing.JToggleButton();
        tbTp5D = new javax.swing.JToggleButton();
        tbTp6S = new javax.swing.JToggleButton();
        tbTp6M = new javax.swing.JToggleButton();
        tbTp6D = new javax.swing.JToggleButton();
        tbTp7S = new javax.swing.JToggleButton();
        tbTp7M = new javax.swing.JToggleButton();
        tbTp7D = new javax.swing.JToggleButton();
        tbTp13S = new javax.swing.JToggleButton();
        tbTp13M = new javax.swing.JToggleButton();
        tbTp13D = new javax.swing.JToggleButton();
        tbTp14S = new javax.swing.JToggleButton();
        tbTp14M = new javax.swing.JToggleButton();
        tbTp14D = new javax.swing.JToggleButton();
        tbTp15S = new javax.swing.JToggleButton();
        tbTp15M = new javax.swing.JToggleButton();
        tbTp15D = new javax.swing.JToggleButton();
        tbTp8S = new javax.swing.JToggleButton();
        tbTp8M = new javax.swing.JToggleButton();
        tbTp8D = new javax.swing.JToggleButton();
        tbTp9S = new javax.swing.JToggleButton();
        tbTp9M = new javax.swing.JToggleButton();
        tbTp9D = new javax.swing.JToggleButton();
        tbTp10S = new javax.swing.JToggleButton();
        tbTp10M = new javax.swing.JToggleButton();
        tbTp10D = new javax.swing.JToggleButton();
        tbTp11S = new javax.swing.JToggleButton();
        tbTp11M = new javax.swing.JToggleButton();
        tbTp11D = new javax.swing.JToggleButton();
        tbTp12S = new javax.swing.JToggleButton();
        tbTp12M = new javax.swing.JToggleButton();
        tbTp12D = new javax.swing.JToggleButton();
        cbTpMonth = new javax.swing.JComboBox<>();
        cbTpHour = new javax.swing.JComboBox<>();
        cbTpMinutes = new javax.swing.JComboBox<>();
        lTp15 = new javax.swing.JLabel();
        lTp1 = new javax.swing.JLabel();
        lTp2 = new javax.swing.JLabel();
        lTp3 = new javax.swing.JLabel();
        lTp4 = new javax.swing.JLabel();
        lTp5 = new javax.swing.JLabel();
        lTp6 = new javax.swing.JLabel();
        lTp7 = new javax.swing.JLabel();
        lTp8 = new javax.swing.JLabel();
        lTp9 = new javax.swing.JLabel();
        lTp10 = new javax.swing.JLabel();
        lTp11 = new javax.swing.JLabel();
        lTp12 = new javax.swing.JLabel();
        lTp13 = new javax.swing.JLabel();
        lTp14 = new javax.swing.JLabel();

        jButton15.setBackground(new java.awt.Color(255, 0, 0));
        jButton15.setText("12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(810, 590));
        setPreferredSize(new java.awt.Dimension(810, 590));

        tpFOHGUIMain.setAutoscrolls(true);
        tpFOHGUIMain.setMinimumSize(new java.awt.Dimension(810, 523));
        tpFOHGUIMain.setPreferredSize(new java.awt.Dimension(810, 523));

        pNotifications.setMinimumSize(new java.awt.Dimension(810, 523));
        pNotifications.setPreferredSize(new java.awt.Dimension(810, 523));

        listNotifications.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        spNotifications.setViewportView(listNotifications);

        bNotificationDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bNotificationDelete.setText("Delete");
        bNotificationDelete.setActionCommand("");
        bNotificationDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNotificationDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pNotificationsLayout = new javax.swing.GroupLayout(pNotifications);
        pNotifications.setLayout(pNotificationsLayout);
        pNotificationsLayout.setHorizontalGroup(
                pNotificationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(spNotifications)
                        .addGroup(pNotificationsLayout.createSequentialGroup()
                                .addGap(346, 346, 346)
                                .addComponent(bNotificationDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                .addGap(348, 348, 348))
        );
        pNotificationsLayout.setVerticalGroup(
                pNotificationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pNotificationsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(spNotifications, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(bNotificationDelete)
                                .addGap(17, 17, 17))
        );

        tpFOHGUIMain.addTab("Notifications", pNotifications);

        pMenu.setMinimumSize(new java.awt.Dimension(810, 523));
        pMenu.setPreferredSize(new java.awt.Dimension(810, 523));

        tMenu.setAutoCreateRowSorter(true);
        tMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tMenu.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "Name", "Price", "Description", "Allergies"
                }
        ) {
            boolean[] canEdit = new boolean [] {
                    false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tMenu.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tMenu.setRowHeight(40);
        tMenu.setRowSelectionAllowed(false);
        tMenu.setShowGrid(true);
        tMenu.setUpdateSelectionOnSort(false);
        tMenu.setVerifyInputWhenFocusTarget(false);
        spMenu.setViewportView(tMenu);

        javax.swing.GroupLayout pMenuLayout = new javax.swing.GroupLayout(pMenu);
        pMenu.setLayout(pMenuLayout);
        pMenuLayout.setHorizontalGroup(
                pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pMenuLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(spMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
                                .addContainerGap())
        );
        pMenuLayout.setVerticalGroup(
                pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pMenuLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(spMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                                .addContainerGap())
        );

        tpFOHGUIMain.addTab("Menu", pMenu);

        pBooking.setMinimumSize(new java.awt.Dimension(810, 523));
        pBooking.setPreferredSize(new java.awt.Dimension(810, 523));

        pNewBooking.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "New Booking:", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        tfNbName.setDragEnabled(true);
        tfNbName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNbNameActionPerformed(evt);
            }
        });

        lNbName.setText("Name:");

        lNbPhoneNumber.setText("Phone Number:");

        tfNbPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNbPhoneNumberActionPerformed(evt);
            }
        });

        lNbNoGuests.setText("Number of Guests:");

        lNbTime.setText("Time:");

        lNbDate.setText("Date:");

        bNbSubmit.setText("SUBMIT");
        bNbSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNbSubmitActionPerformed(evt);
            }
        });

        lNbTables.setText("Tables:");

        cbNbDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cbNbMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        cbNbYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        cbNbHour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", " " }));

        cbNbMinute.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "15", "30", "45" }));

        cbNbNoGuests.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));

        lNbBookingLength.setText("Booking Length:");

        cbNbBookingLength.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1:00", "1:15", "1:30", "1:45", "2:00", "2:15", "2:30", "2:45", "3:00" }));

        tfTables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTablesActionPerformed(evt);
            }
        });

        lNbWaiter.setText("Waiter:");

        javax.swing.GroupLayout pNewBookingLayout = new javax.swing.GroupLayout(pNewBooking);
        pNewBooking.setLayout(pNewBookingLayout);
        pNewBookingLayout.setHorizontalGroup(
                pNewBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pNewBookingLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cbNbDay, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbNbMonth, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbNbYear, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(pNewBookingLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pNewBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pNewBookingLayout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(cbNbBookingLength, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(36, 36, 36))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pNewBookingLayout.createSequentialGroup()
                                                .addGroup(pNewBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lNbBookingLength, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(pNewBookingLayout.createSequentialGroup()
                                                                .addGap(15, 15, 15)
                                                                .addComponent(cbNbHour, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                .addGap(27, 27, 27)))
                                .addGroup(pNewBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lNbNoGuests, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(pNewBookingLayout.createSequentialGroup()
                                                .addComponent(cbNbNoGuests, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(27, 27, 27))
                                        .addGroup(pNewBookingLayout.createSequentialGroup()
                                                .addComponent(cbNbMinute, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(19, 19, 19)))
                                .addGap(15, 15, 15))
                        .addGroup(pNewBookingLayout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(lNbName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(98, 98, 98))
                        .addGroup(pNewBookingLayout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(lNbPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(69, 69, 69))
                        .addGroup(pNewBookingLayout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(lNbDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(102, 102, 102))
                        .addGroup(pNewBookingLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(tfTables)
                                .addGap(55, 55, 55))
                        .addGroup(pNewBookingLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(pNewBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tfNbPhoneNumber)
                                        .addComponent(tfNbName))
                                .addGap(31, 31, 31))
                        .addGroup(pNewBookingLayout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(lNbTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(94, 94, 94))
                        .addGroup(pNewBookingLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(pNewBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(bNbSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbNbWaiter, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(66, 66, 66))
                        .addGroup(pNewBookingLayout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(lNbWaiter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(pNewBookingLayout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(lNbTables, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        pNewBookingLayout.setVerticalGroup(
                pNewBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pNewBookingLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lNbName, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNbName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lNbPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNbPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lNbDate, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pNewBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cbNbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbNbDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbNbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lNbTime, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pNewBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cbNbMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbNbHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pNewBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lNbBookingLength, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lNbNoGuests, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pNewBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cbNbBookingLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbNbNoGuests, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lNbTables, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfTables, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lNbWaiter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbNbWaiter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(bNbSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        pEditBooking.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edit Booking:", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        pEditBooking.setAutoscrolls(true);

        bBookingDelete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bBookingDelete.setText("DELETE");
        bBookingDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBookingDeleteActionPerformed(evt);
            }
        });

        tBookings.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        tBookings.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null}
                },
                new String [] {
                        "Name", "Phone No", "No. Guests", "Time", "Date", "Table", "Waiter", "Length"
                }
        ));
        spEditBooking.setViewportView(tBookings);

        cbBookingsSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tonight's Bookings", "Tomorrow's Bookings", "All Bookings" }));

        bBookingEdit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bBookingEdit.setText("EDIT");

        javax.swing.GroupLayout pEditBookingLayout = new javax.swing.GroupLayout(pEditBooking);
        pEditBooking.setLayout(pEditBookingLayout);
        pEditBookingLayout.setHorizontalGroup(
                pEditBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(spEditBooking, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                        .addGroup(pEditBookingLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(bBookingDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(145, 145, 145)
                                .addComponent(bBookingEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(73, 73, 73))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pEditBookingLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbBookingsSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(179, 179, 179))
        );
        pEditBookingLayout.setVerticalGroup(
                pEditBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pEditBookingLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(cbBookingsSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spEditBooking, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(pEditBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(bBookingDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bBookingEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout pBookingLayout = new javax.swing.GroupLayout(pBooking);
        pBooking.setLayout(pBookingLayout);
        pBookingLayout.setHorizontalGroup(
                pBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pBookingLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pNewBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pEditBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        pBookingLayout.setVerticalGroup(
                pBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pBookingLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(pEditBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pNewBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );

        tpFOHGUIMain.addTab("Booking", pBooking);

        pPayment.setMinimumSize(new java.awt.Dimension(810, 523));
        pPayment.setPreferredSize(new java.awt.Dimension(810, 523));

        listUnpaidOrders.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        listUnpaidOrders.setMaximumSize(new java.awt.Dimension(10000, 10000));
        listUnpaidOrders.setMinimumSize(new java.awt.Dimension(332, 280));
        listUnpaidOrders.setPreferredSize(new java.awt.Dimension(332, 280));
        spUnpaidOrders.setViewportView(listUnpaidOrders);

        lUnpaidOrders.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lUnpaidOrders.setText("Unpaid Orders:");

        bPrintBill.setText("Print Bill");
        bPrintBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPrintBillActionPerformed(evt);
            }
        });

        bSelectBill.setText("Select Bill");
        bSelectBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSelectBillActionPerformed(evt);
            }
        });

        taSelectedBill.setColumns(20);
        taSelectedBill.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        taSelectedBill.setRows(5);
        taSelectedBill.setMinimumSize(new java.awt.Dimension(332, 280));
        taSelectedBill.setPreferredSize(new java.awt.Dimension(332, 280));
        spSelectedBill.setViewportView(taSelectedBill);

        lSelectedBill.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lSelectedBill.setText("Selected Bill:");

        bPayWholeBill.setText("Pay Whole Bill");
        bPayWholeBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPayWholeBillActionPerformed(evt);
            }
        });

        bPaySplitBill.setText("Pay Split Bill");
        bPaySplitBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPaySplitBillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pPaymentLayout = new javax.swing.GroupLayout(pPayment);
        pPayment.setLayout(pPaymentLayout);
        pPaymentLayout.setHorizontalGroup(
                pPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pPaymentLayout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(lUnpaidOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(395, 395, 395)
                                .addComponent(lSelectedBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(139, 139, 139))
                        .addGroup(pPaymentLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(spUnpaidOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(61, 61, 61)
                                .addGroup(pPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(bSelectBill, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bPrintBill, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bPayWholeBill)
                                        .addComponent(bPaySplitBill))
                                .addGap(63, 63, 63)
                                .addComponent(spSelectedBill, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(29, 29, 29))
        );

        pPaymentLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bPaySplitBill, bPayWholeBill, bPrintBill, bSelectBill});

        pPaymentLayout.setVerticalGroup(
                pPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pPaymentLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(pPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lUnpaidOrders, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lSelectedBill, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pPaymentLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(pPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(spSelectedBill)
                                                        .addComponent(spUnpaidOrders, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE))
                                                .addGap(41, 41, 41))
                                        .addGroup(pPaymentLayout.createSequentialGroup()
                                                .addGap(89, 89, 89)
                                                .addComponent(bSelectBill)
                                                .addGap(42, 42, 42)
                                                .addComponent(bPrintBill)
                                                .addGap(51, 51, 51)
                                                .addComponent(bPaySplitBill)
                                                .addGap(49, 49, 49)
                                                .addComponent(bPayWholeBill)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        tpFOHGUIMain.addTab("Payment", pPayment);

        pOrder.setMinimumSize(new java.awt.Dimension(810, 523));
        pOrder.setPreferredSize(new java.awt.Dimension(810, 523));

        lOrders.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lOrders.setText("Orders:");

        bOEdit.setText("Edit");
        bOEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOEditActionPerformed(evt);
            }
        });

        bODelete.setText("Delete");

        bONewOrder.setText("New Order");
        bONewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bONewOrderActionPerformed(evt);
            }
        });

        tOrders.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null}
                },
                new String [] {
                        "BookingID", "Cover", "Table", "Items", "Note", "Waiter"
                }
        ) {
            boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tOrders.setMinimumSize(new java.awt.Dimension(300, 390));
        tOrders.setPreferredSize(new java.awt.Dimension(300, 390));
        spOrders.setViewportView(tOrders);

        javax.swing.GroupLayout pOrderLayout = new javax.swing.GroupLayout(pOrder);
        pOrder.setLayout(pOrderLayout);
        pOrderLayout.setHorizontalGroup(
                pOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pOrderLayout.createSequentialGroup()
                                .addGroup(pOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pOrderLayout.createSequentialGroup()
                                                .addGap(346, 346, 346)
                                                .addComponent(lOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(363, 363, 363))
                                        .addGroup(pOrderLayout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addComponent(spOrders)))
                                .addGap(39, 39, 39))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pOrderLayout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(bOEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(132, 132, 132)
                                .addComponent(bODelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(139, 139, 139)
                                .addComponent(bONewOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(158, 158, 158))
        );
        pOrderLayout.setVerticalGroup(
                pOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pOrderLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(spOrders, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(pOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bOEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bODelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bONewOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(31, 31, 31))
        );

        tpFOHGUIMain.addTab("Order", pOrder);

        pTablePlan.setMinimumSize(new java.awt.Dimension(810, 523));
        pTablePlan.setPreferredSize(new java.awt.Dimension(810, 523));
        pTablePlan.setLayout(null);

        bTable9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bTable9.setText("9");
        pTablePlan.add(bTable9);
        bTable9.setBounds(278, 186, 112, 64);

        bTable13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bTable13.setText("13");
        pTablePlan.add(bTable13);
        bTable13.setBounds(18, 330, 112, 62);

        bTable1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bTable1.setText("1");
        pTablePlan.add(bTable1);
        bTable1.setBounds(18, 34, 112, 68);

        bTable6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bTable6.setText("6");
        pTablePlan.add(bTable6);
        bTable6.setBounds(668, 36, 112, 66);

        bTable15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bTable15.setText("15");
        pTablePlan.add(bTable15);
        bTable15.setBounds(278, 328, 112, 64);

        bTable14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bTable14.setText("14");
        pTablePlan.add(bTable14);
        bTable14.setBounds(148, 330, 112, 62);

        bTable5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bTable5.setText("5");
        pTablePlan.add(bTable5);
        bTable5.setBounds(538, 36, 112, 66);

        bTable2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bTable2.setText("2");
        pTablePlan.add(bTable2);
        bTable2.setBounds(148, 34, 112, 68);

        bTable4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bTable4.setText("4");
        pTablePlan.add(bTable4);
        bTable4.setBounds(408, 36, 112, 66);

        bTable12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bTable12.setText("12");
        pTablePlan.add(bTable12);
        bTable12.setBounds(668, 186, 112, 64);

        bTable8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bTable8.setText("8");
        pTablePlan.add(bTable8);
        bTable8.setBounds(148, 186, 112, 64);

        bTable10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bTable10.setText("10");
        pTablePlan.add(bTable10);
        bTable10.setBounds(408, 186, 112, 64);

        bTable11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bTable11.setText("11");
        pTablePlan.add(bTable11);
        bTable11.setBounds(538, 186, 112, 64);

        bTable3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bTable3.setText("3");
        pTablePlan.add(bTable3);
        bTable3.setBounds(278, 34, 112, 68);

        bTable7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bTable7.setText("7");
        pTablePlan.add(bTable7);
        bTable7.setBounds(18, 186, 112, 64);

        cbTpDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "2023", "2024", "2025", "2026", "2027", "2028", "2029" }));
        pTablePlan.add(cbTpDay);
        cbTpDay.setBounds(632, 330, 70, 22);

        cbTpYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        pTablePlan.add(cbTpYear);
        cbTpYear.setBounds(438, 330, 72, 22);

        tbTp1S.setText("S");
        pTablePlan.add(tbTp1S);
        tbTp1S.setBounds(20, 108, 36, 23);

        tbTp1M.setText("M");
        pTablePlan.add(tbTp1M);
        tbTp1M.setBounds(56, 108, 38, 23);

        tbTp1D.setText("D");
        pTablePlan.add(tbTp1D);
        tbTp1D.setBounds(94, 108, 38, 23);

        tbTp2S.setText("S");
        pTablePlan.add(tbTp2S);
        tbTp2S.setBounds(150, 108, 38, 23);

        tbTp2M.setText("M");
        pTablePlan.add(tbTp2M);
        tbTp2M.setBounds(188, 108, 38, 23);

        tbTp2D.setText("D");
        pTablePlan.add(tbTp2D);
        tbTp2D.setBounds(226, 108, 38, 23);

        tbTp3S.setText("S");
        pTablePlan.add(tbTp3S);
        tbTp3S.setBounds(280, 108, 38, 23);

        tbTp3M.setText("M");
        tbTp3M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTp3MActionPerformed(evt);
            }
        });
        pTablePlan.add(tbTp3M);
        tbTp3M.setBounds(316, 108, 38, 23);

        tbTp3D.setText("D");
        pTablePlan.add(tbTp3D);
        tbTp3D.setBounds(354, 108, 38, 23);

        tbTp4S.setText("S");
        pTablePlan.add(tbTp4S);
        tbTp4S.setBounds(410, 108, 38, 23);

        tbTp4M.setText("M");
        pTablePlan.add(tbTp4M);
        tbTp4M.setBounds(446, 108, 38, 23);

        tbTp4D.setText("D");
        pTablePlan.add(tbTp4D);
        tbTp4D.setBounds(482, 108, 38, 23);

        tbTp5S.setText("S");
        pTablePlan.add(tbTp5S);
        tbTp5S.setBounds(542, 108, 38, 23);

        tbTp5M.setText("M");
        pTablePlan.add(tbTp5M);
        tbTp5M.setBounds(580, 108, 38, 23);

        tbTp5D.setText("D");
        pTablePlan.add(tbTp5D);
        tbTp5D.setBounds(616, 108, 38, 23);

        tbTp6S.setText("S");
        pTablePlan.add(tbTp6S);
        tbTp6S.setBounds(672, 108, 38, 23);

        tbTp6M.setText("M");
        pTablePlan.add(tbTp6M);
        tbTp6M.setBounds(710, 108, 38, 23);

        tbTp6D.setText("D");
        pTablePlan.add(tbTp6D);
        tbTp6D.setBounds(746, 108, 38, 23);

        tbTp7S.setText("S");
        pTablePlan.add(tbTp7S);
        tbTp7S.setBounds(20, 256, 38, 23);

        tbTp7M.setText("M");
        tbTp7M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTp7MActionPerformed(evt);
            }
        });
        pTablePlan.add(tbTp7M);
        tbTp7M.setBounds(56, 256, 38, 23);

        tbTp7D.setText("D");
        tbTp7D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTp7DActionPerformed(evt);
            }
        });
        pTablePlan.add(tbTp7D);
        tbTp7D.setBounds(92, 256, 38, 23);

        tbTp13S.setText("S");
        pTablePlan.add(tbTp13S);
        tbTp13S.setBounds(20, 398, 38, 23);

        tbTp13M.setText("M");
        pTablePlan.add(tbTp13M);
        tbTp13M.setBounds(56, 398, 38, 23);

        tbTp13D.setText("D");
        pTablePlan.add(tbTp13D);
        tbTp13D.setBounds(92, 398, 38, 23);

        tbTp14S.setText("S");
        pTablePlan.add(tbTp14S);
        tbTp14S.setBounds(150, 398, 38, 23);

        tbTp14M.setText("M");
        tbTp14M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTp14MActionPerformed(evt);
            }
        });
        pTablePlan.add(tbTp14M);
        tbTp14M.setBounds(186, 398, 38, 23);

        tbTp14D.setText("D");
        pTablePlan.add(tbTp14D);
        tbTp14D.setBounds(222, 398, 38, 23);

        tbTp15S.setText("S");
        pTablePlan.add(tbTp15S);
        tbTp15S.setBounds(280, 398, 38, 23);

        tbTp15M.setText("M");
        pTablePlan.add(tbTp15M);
        tbTp15M.setBounds(316, 398, 38, 23);

        tbTp15D.setText("D");
        pTablePlan.add(tbTp15D);
        tbTp15D.setBounds(352, 398, 38, 23);

        tbTp8S.setText("S");
        pTablePlan.add(tbTp8S);
        tbTp8S.setBounds(148, 258, 38, 23);

        tbTp8M.setText("M");
        pTablePlan.add(tbTp8M);
        tbTp8M.setBounds(186, 258, 38, 23);

        tbTp8D.setText("D");
        pTablePlan.add(tbTp8D);
        tbTp8D.setBounds(222, 258, 38, 23);

        tbTp9S.setText("S");
        pTablePlan.add(tbTp9S);
        tbTp9S.setBounds(280, 258, 38, 23);

        tbTp9M.setText("M");
        pTablePlan.add(tbTp9M);
        tbTp9M.setBounds(318, 258, 38, 23);

        tbTp9D.setText("D");
        pTablePlan.add(tbTp9D);
        tbTp9D.setBounds(354, 258, 38, 23);

        tbTp10S.setText("S");
        pTablePlan.add(tbTp10S);
        tbTp10S.setBounds(410, 258, 38, 23);

        tbTp10M.setText("M");
        pTablePlan.add(tbTp10M);
        tbTp10M.setBounds(446, 258, 38, 23);

        tbTp10D.setText("D");
        pTablePlan.add(tbTp10D);
        tbTp10D.setBounds(484, 258, 38, 23);

        tbTp11S.setText("S");
        pTablePlan.add(tbTp11S);
        tbTp11S.setBounds(540, 258, 38, 23);

        tbTp11M.setText("M");
        pTablePlan.add(tbTp11M);
        tbTp11M.setBounds(576, 258, 38, 23);

        tbTp11D.setText("D");
        pTablePlan.add(tbTp11D);
        tbTp11D.setBounds(612, 258, 38, 23);

        tbTp12S.setText("S");
        pTablePlan.add(tbTp12S);
        tbTp12S.setBounds(670, 256, 38, 23);

        tbTp12M.setText("M");
        pTablePlan.add(tbTp12M);
        tbTp12M.setBounds(708, 256, 38, 23);

        tbTp12D.setText("D");
        pTablePlan.add(tbTp12D);
        tbTp12D.setBounds(744, 256, 38, 23);

        cbTpMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        pTablePlan.add(cbTpMonth);
        cbTpMonth.setBounds(536, 330, 72, 22);

        cbTpHour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hour", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21" }));
        pTablePlan.add(cbTpHour);
        cbTpHour.setBounds(486, 370, 70, 22);

        cbTpMinutes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Minutes", "00", "15", "30", "45" }));
        pTablePlan.add(cbTpMinutes);
        cbTpMinutes.setBounds(582, 370, 78, 22);

        lTp15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lTp15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTp15.setText("Angela");
        pTablePlan.add(lTp15);
        lTp15.setBounds(292, 308, 86, 16);

        lTp1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lTp1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTp1.setText("Angela");
        pTablePlan.add(lTp1);
        lTp1.setBounds(30, 14, 86, 20);

        lTp2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lTp2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTp2.setText("Patrice");
        pTablePlan.add(lTp2);
        lTp2.setBounds(162, 14, 86, 16);

        lTp3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lTp3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTp3.setText("Patrice");
        pTablePlan.add(lTp3);
        lTp3.setBounds(292, 14, 86, 16);

        lTp4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lTp4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTp4.setText("Alfonse");
        pTablePlan.add(lTp4);
        lTp4.setBounds(418, 16, 86, 16);

        lTp5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lTp5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTp5.setText("Alfonse");
        pTablePlan.add(lTp5);
        lTp5.setBounds(550, 16, 86, 16);

        lTp6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lTp6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTp6.setText("Angela");
        pTablePlan.add(lTp6);
        lTp6.setBounds(682, 16, 86, 16);

        lTp7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lTp7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTp7.setText("Angela");
        pTablePlan.add(lTp7);
        lTp7.setBounds(32, 164, 86, 16);

        lTp8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lTp8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTp8.setText("Angela");
        pTablePlan.add(lTp8);
        lTp8.setBounds(162, 166, 86, 16);

        lTp9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lTp9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTp9.setText("Patrice");
        pTablePlan.add(lTp9);
        lTp9.setBounds(292, 166, 86, 16);

        lTp10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lTp10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTp10.setText("Angela");
        pTablePlan.add(lTp10);
        lTp10.setBounds(422, 166, 86, 16);

        lTp11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lTp11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTp11.setText("Angela");
        pTablePlan.add(lTp11);
        lTp11.setBounds(550, 166, 86, 16);

        lTp12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lTp12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTp12.setText("Patrice");
        pTablePlan.add(lTp12);
        lTp12.setBounds(682, 166, 86, 16);

        lTp13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lTp13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTp13.setText("Alfonse");
        pTablePlan.add(lTp13);
        lTp13.setBounds(32, 310, 86, 16);

        lTp14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lTp14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTp14.setText("Alfonse");
        pTablePlan.add(lTp14);
        lTp14.setBounds(162, 310, 86, 16);

        tpFOHGUIMain.addTab("Table Plan", pTablePlan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tpFOHGUIMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tpFOHGUIMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void bNotificationDeleteActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        listNotifications.remove(listNotifications.getSelectedIndex());
    }

    private void bBookingDeleteActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void tfNbNameActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void tfNbPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void bPrintBillActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void bSelectBillActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int bookingId = listUnpaidOrders.getSelectedValue();
        booking =BookingCollection.get(bookingId);
        int[] covers = booking.getCovers();
        int coversLength = covers.length;
        for (int i = 0; i < coversLength; i++) {
            taSelectedBill.append((i+1) + ". " + covers[i] + "\n");
        }

    }
    private void bPayWholeBillActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (booking != null){
            Terminal.payWholeBill(booking.getBookingId(), false);
        }

    }
    private void bPaySplitBillActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (booking != null){
            Terminal.paySplitBill(booking.getBookingId(), false);
        }

    }

    private void bOEditActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void bONewOrderActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        NewOrder order = new NewOrder();
        order.setVisible(true);
    }

    private void tfTablesActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void tbTp3MActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void tbTp7MActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void tbTp14MActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void tbTp7DActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }



    private void bNbSubmitActionPerformed(java.awt.event.ActionEvent evt) {
        // Retrieve values from form components
        String customerName = tfNbName.getText();
        String phoneNumber = tfNbPhoneNumber.getText();
        int waiterId = Integer.parseInt(cbNbWaiter.getSelectedItem().toString()); // Parse the waiter ID from the dropdown

        // Combine date and time to create a start timestamp
        String date = cbNbYear.getSelectedItem().toString() + "-" +
                cbNbMonth.getSelectedItem().toString() + "-" +
                cbNbDay.getSelectedItem().toString();
        String time = cbNbHour.getSelectedItem().toString() + ":" +
                cbNbMinute.getSelectedItem().toString();

        // Convert date and time strings to timestamp
        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm");
            Date parsedDate = dateFormat.parse(date + " " + time);
            long startTimestamp = parsedDate.getTime() / 1000;  // Convert milliseconds to seconds

            // Assume booking length is in hours and minutes (HH:mm), and calculate end timestamp in seconds
            String[] bookingLengthParts = cbNbBookingLength.getSelectedItem().toString().split(":");
            long bookingLengthSeconds = Integer.parseInt(bookingLengthParts[0]) * 3600 + // Hours to seconds
                    Integer.parseInt(bookingLengthParts[1]) * 60;     // Minutes to seconds
            long endTimeStamp = startTimestamp + bookingLengthSeconds;

            // Parse the number of guests
            int covers = Integer.parseInt(cbNbNoGuests.getSelectedItem().toString());

            // Parse table numbers from textField into an array of integers
            String[] tableStrings = tfTables.getText().split(",");
            int[] tables = new int[tableStrings.length];
            for (int i = 0; i < tableStrings.length; i++) {
                tables[i] = Integer.parseInt(tableStrings[i].trim());
            }

            // Call the newBooking method from Terminal class
            boolean success = Terminal.newBooking(customerName, phoneNumber, waiterId, startTimestamp, endTimeStamp, tables, covers);

            // Handle the response
            if (success) {
                JOptionPane.showMessageDialog(null, "Booking successfully created!");
                // Update the booking table
                updateBookingTable(tBookings);  // Assuming 'tBookings' is your JTable variable
            } else {
                JOptionPane.showMessageDialog(null, "Failed to create booking.");
            }
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, "Failed to parse date/time.");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid number format in inputs.");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Terminal.initialise();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabbedGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabbedGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabbedGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabbedGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabbedGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton bBookingDelete;
    private javax.swing.JButton bBookingEdit;
    private javax.swing.JButton bNbSubmit;
    private javax.swing.JButton bNotificationDelete;
    private javax.swing.JButton bODelete;
    private javax.swing.JButton bOEdit;
    private javax.swing.JButton bONewOrder;
    private javax.swing.JButton bPaySplitBill;
    private javax.swing.JButton bPayWholeBill;
    private javax.swing.JButton bPrintBill;
    private javax.swing.JButton bSelectBill;
    private javax.swing.JButton bTable1;
    private javax.swing.JButton bTable10;
    private javax.swing.JButton bTable11;
    private javax.swing.JButton bTable12;
    private javax.swing.JButton bTable13;
    private javax.swing.JButton bTable14;
    private javax.swing.JButton bTable15;
    private javax.swing.JButton bTable2;
    private javax.swing.JButton bTable3;
    private javax.swing.JButton bTable4;
    private javax.swing.JButton bTable5;
    private javax.swing.JButton bTable6;
    private javax.swing.JButton bTable7;
    private javax.swing.JButton bTable8;
    private javax.swing.JButton bTable9;
    private javax.swing.JComboBox<String> cbBookingsSelect;
    private javax.swing.JComboBox<String> cbNbBookingLength;
    private javax.swing.JComboBox<String> cbNbDay;
    private javax.swing.JComboBox<String> cbNbHour;
    private javax.swing.JComboBox<String> cbNbMinute;
    private javax.swing.JComboBox<String> cbNbMonth;
    private javax.swing.JComboBox<String> cbNbNoGuests;
    private javax.swing.JComboBox<String> cbNbWaiter;
    private javax.swing.JComboBox<String> cbNbYear;
    private javax.swing.JComboBox<String> cbTpDay;
    private javax.swing.JComboBox<String> cbTpHour;
    private javax.swing.JComboBox<String> cbTpMinutes;
    private javax.swing.JComboBox<String> cbTpMonth;
    private javax.swing.JComboBox<String> cbTpYear;
    private javax.swing.JButton jButton15;
    private javax.swing.JLabel lNbBookingLength;
    private javax.swing.JLabel lNbDate;
    private javax.swing.JLabel lNbName;
    private javax.swing.JLabel lNbNoGuests;
    private javax.swing.JLabel lNbPhoneNumber;
    private javax.swing.JLabel lNbTables;
    private javax.swing.JLabel lNbTime;
    private javax.swing.JLabel lNbWaiter;
    private javax.swing.JLabel lOrders;
    private javax.swing.JLabel lSelectedBill;
    private javax.swing.JLabel lTp1;
    private javax.swing.JLabel lTp10;
    private javax.swing.JLabel lTp11;
    private javax.swing.JLabel lTp12;
    private javax.swing.JLabel lTp13;
    private javax.swing.JLabel lTp14;
    private javax.swing.JLabel lTp15;
    private javax.swing.JLabel lTp2;
    private javax.swing.JLabel lTp3;
    private javax.swing.JLabel lTp4;
    private javax.swing.JLabel lTp5;
    private javax.swing.JLabel lTp6;
    private javax.swing.JLabel lTp7;
    private javax.swing.JLabel lTp8;
    private javax.swing.JLabel lTp9;
    private javax.swing.JLabel lUnpaidOrders;
    private javax.swing.JList<String> listNotifications;
    private javax.swing.JList<Integer> listUnpaidOrders;
    private javax.swing.JPanel pBooking;
    private javax.swing.JPanel pEditBooking;
    private javax.swing.JPanel pMenu;
    private javax.swing.JPanel pNewBooking;
    private javax.swing.JPanel pNotifications;
    private javax.swing.JPanel pOrder;
    private javax.swing.JPanel pPayment;
    private javax.swing.JPanel pTablePlan;
    private javax.swing.JScrollPane spEditBooking;
    private javax.swing.JScrollPane spMenu;
    private javax.swing.JScrollPane spNotifications;
    private javax.swing.JScrollPane spOrders;
    private javax.swing.JScrollPane spSelectedBill;
    private javax.swing.JScrollPane spUnpaidOrders;
    private javax.swing.JTable tBookings;
    private javax.swing.JTable tMenu;
    private javax.swing.JTable tOrders;
    private javax.swing.JTextArea taSelectedBill;
    private javax.swing.JToggleButton tbTp10D;
    private javax.swing.JToggleButton tbTp10M;
    private javax.swing.JToggleButton tbTp10S;
    private javax.swing.JToggleButton tbTp11D;
    private javax.swing.JToggleButton tbTp11M;
    private javax.swing.JToggleButton tbTp11S;
    private javax.swing.JToggleButton tbTp12D;
    private javax.swing.JToggleButton tbTp12M;
    private javax.swing.JToggleButton tbTp12S;
    private javax.swing.JToggleButton tbTp13D;
    private javax.swing.JToggleButton tbTp13M;
    private javax.swing.JToggleButton tbTp13S;
    private javax.swing.JToggleButton tbTp14D;
    private javax.swing.JToggleButton tbTp14M;
    private javax.swing.JToggleButton tbTp14S;
    private javax.swing.JToggleButton tbTp15D;
    private javax.swing.JToggleButton tbTp15M;
    private javax.swing.JToggleButton tbTp15S;
    private javax.swing.JToggleButton tbTp1D;
    private javax.swing.JToggleButton tbTp1M;
    private javax.swing.JToggleButton tbTp1S;
    private javax.swing.JToggleButton tbTp2D;
    private javax.swing.JToggleButton tbTp2M;
    private javax.swing.JToggleButton tbTp2S;
    private javax.swing.JToggleButton tbTp3D;
    private javax.swing.JToggleButton tbTp3M;
    private javax.swing.JToggleButton tbTp3S;
    private javax.swing.JToggleButton tbTp4D;
    private javax.swing.JToggleButton tbTp4M;
    private javax.swing.JToggleButton tbTp4S;
    private javax.swing.JToggleButton tbTp5D;
    private javax.swing.JToggleButton tbTp5M;
    private javax.swing.JToggleButton tbTp5S;
    private javax.swing.JToggleButton tbTp6D;
    private javax.swing.JToggleButton tbTp6M;
    private javax.swing.JToggleButton tbTp6S;
    private javax.swing.JToggleButton tbTp7D;
    private javax.swing.JToggleButton tbTp7M;
    private javax.swing.JToggleButton tbTp7S;
    private javax.swing.JToggleButton tbTp8D;
    private javax.swing.JToggleButton tbTp8M;
    private javax.swing.JToggleButton tbTp8S;
    private javax.swing.JToggleButton tbTp9D;
    private javax.swing.JToggleButton tbTp9M;
    private javax.swing.JToggleButton tbTp9S;
    private javax.swing.JTextField tfNbName;
    private javax.swing.JTextField tfNbPhoneNumber;
    private javax.swing.JTextField tfTables;
    private javax.swing.JTabbedPane tpFOHGUIMain;
    // End of variables declaration
}
