/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lancastersguiv2;

/**
 *
 * @author josep
 */
public class TabbedGUI extends javax.swing.JFrame {

    /**
     * Creates new form TabbedGUI
     */
    public TabbedGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jButton15 = new javax.swing.JButton();
        tpFOHGUIMain = new javax.swing.JTabbedPane();
        pNotifications = new javax.swing.JPanel();
        spNotifications = new javax.swing.JScrollPane();
        listNotifications = new javax.swing.JList<>();
        bNotificationDelete = new javax.swing.JButton();
        pMenu = new javax.swing.JPanel();
        spMenu = new javax.swing.JScrollPane();
        tMenu = new javax.swing.JTable();
        pBooking = new javax.swing.JPanel();
        pNewBooking = new javax.swing.JPanel();
        tfNbName = new javax.swing.JTextField();
        lNbName = new javax.swing.JLabel();
        lNbPhoneNumber = new javax.swing.JLabel();
        tfNbPhoneNumber = new javax.swing.JTextField();
        lNbNoGuests = new javax.swing.JLabel();
        lNbTime = new javax.swing.JLabel();
        lNbDate = new javax.swing.JLabel();
        bNbSubmit = new javax.swing.JButton();
        lNbTables = new javax.swing.JLabel();
        cbNbDay = new javax.swing.JComboBox<>();
        cbNbMonth = new javax.swing.JComboBox<>();
        cbNbYear = new javax.swing.JComboBox<>();
        cbNbHour = new javax.swing.JComboBox<>();
        cbNbMinute = new javax.swing.JComboBox<>();
        cbNbNoGuests = new javax.swing.JComboBox<>();
        lNbBookingLength = new javax.swing.JLabel();
        cbNbBookingLength = new javax.swing.JComboBox<>();
        tfTables = new javax.swing.JTextField();
        lNbWaiter = new javax.swing.JLabel();
        cbNbWaiter = new javax.swing.JComboBox<>();
        pEditBooking = new javax.swing.JPanel();
        bBookingDelete = new javax.swing.JButton();
        spEditBooking = new javax.swing.JScrollPane();
        tBookings = new javax.swing.JTable();
        cbBookingsSelect = new javax.swing.JComboBox<>();
        bBookingEdit = new javax.swing.JButton();
        pPayment = new javax.swing.JPanel();
        spUnpaidOrders = new javax.swing.JScrollPane();
        listUnpaidOrders = new javax.swing.JList<>();
        lUnpaidOrders = new javax.swing.JLabel();
        bPrintBill = new javax.swing.JButton();
        bEditBill = new javax.swing.JButton();
        spSelectedBill = new javax.swing.JScrollPane();
        listSelectedBill = new javax.swing.JTextArea();
        lSelectedBill = new javax.swing.JLabel();
        bBillHistory = new javax.swing.JButton();
        bSplitBill = new javax.swing.JButton();
        pOrder = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lOrders = new javax.swing.JLabel();
        bOEdit = new javax.swing.JButton();
        bODelete = new javax.swing.JButton();
        bOArchive = new javax.swing.JButton();
        bONewOrder = new javax.swing.JButton();
        spOrders = new javax.swing.JScrollPane();
        tOrders = new javax.swing.JTable();
        pTablePlan = new javax.swing.JPanel();
        bTable9 = new javax.swing.JButton();
        bTable13 = new javax.swing.JButton();
        bTable1 = new javax.swing.JButton();
        bTable6 = new javax.swing.JButton();
        bTable15 = new javax.swing.JButton();
        bTable14 = new javax.swing.JButton();
        bTable5 = new javax.swing.JButton();
        bTable2 = new javax.swing.JButton();
        bTable4 = new javax.swing.JButton();
        bTable12 = new javax.swing.JButton();
        bTable8 = new javax.swing.JButton();
        bTable10 = new javax.swing.JButton();
        bTable11 = new javax.swing.JButton();
        bTable3 = new javax.swing.JButton();
        bTable7 = new javax.swing.JButton();
        cbTpDay = new javax.swing.JComboBox<>();
        cbTpYear = new javax.swing.JComboBox<>();
        tbTp1S = new javax.swing.JToggleButton();
        tbTp1M = new javax.swing.JToggleButton();
        tbTp1D = new javax.swing.JToggleButton();
        tbTp2S = new javax.swing.JToggleButton();
        tbTp2M = new javax.swing.JToggleButton();
        tbTp2D = new javax.swing.JToggleButton();
        tbTp3S = new javax.swing.JToggleButton();
        tbTp3M = new javax.swing.JToggleButton();
        tbTp3D = new javax.swing.JToggleButton();
        tbTp4S = new javax.swing.JToggleButton();
        tbTp4M = new javax.swing.JToggleButton();
        tbTp4D = new javax.swing.JToggleButton();
        tbTp5S = new javax.swing.JToggleButton();
        tbTp5M = new javax.swing.JToggleButton();
        tbTp5D = new javax.swing.JToggleButton();
        tbTp6S = new javax.swing.JToggleButton();
        tbTp6M = new javax.swing.JToggleButton();
        tbTp6D = new javax.swing.JToggleButton();
        tbTp7S = new javax.swing.JToggleButton();
        tbTp7M = new javax.swing.JToggleButton();
        tbTp7D = new javax.swing.JToggleButton();
        tbTp13S = new javax.swing.JToggleButton();
        tbTp13M = new javax.swing.JToggleButton();
        tbTp13D = new javax.swing.JToggleButton();
        tbTp14S = new javax.swing.JToggleButton();
        tbTp14M = new javax.swing.JToggleButton();
        tbTp14D = new javax.swing.JToggleButton();
        tbTp15S = new javax.swing.JToggleButton();
        tbTp15M = new javax.swing.JToggleButton();
        tbTp15D = new javax.swing.JToggleButton();
        tbTp8S = new javax.swing.JToggleButton();
        tbTp8M = new javax.swing.JToggleButton();
        tbTp8D = new javax.swing.JToggleButton();
        tbTp9S = new javax.swing.JToggleButton();
        tbTp9M = new javax.swing.JToggleButton();
        tbTp9D = new javax.swing.JToggleButton();
        tbTp10S = new javax.swing.JToggleButton();
        tbTp10M = new javax.swing.JToggleButton();
        tbTp10D = new javax.swing.JToggleButton();
        tbTp11S = new javax.swing.JToggleButton();
        tbTp11M = new javax.swing.JToggleButton();
        tbTp11D = new javax.swing.JToggleButton();
        tbTp12S = new javax.swing.JToggleButton();
        tbTp12M = new javax.swing.JToggleButton();
        tbTp12D = new javax.swing.JToggleButton();
        cbTpMonth = new javax.swing.JComboBox<>();
        cbTpHour = new javax.swing.JComboBox<>();
        cbTpMinutes = new javax.swing.JComboBox<>();
        lTp15 = new javax.swing.JLabel();
        lTp1 = new javax.swing.JLabel();
        lTp2 = new javax.swing.JLabel();
        lTp3 = new javax.swing.JLabel();
        lTp4 = new javax.swing.JLabel();
        lTp5 = new javax.swing.JLabel();
        lTp6 = new javax.swing.JLabel();
        lTp7 = new javax.swing.JLabel();
        lTp8 = new javax.swing.JLabel();
        lTp9 = new javax.swing.JLabel();
        lTp10 = new javax.swing.JLabel();
        lTp11 = new javax.swing.JLabel();
        lTp12 = new javax.swing.JLabel();
        lTp13 = new javax.swing.JLabel();
        lTp14 = new javax.swing.JLabel();

        jButton15.setBackground(new java.awt.Color(255, 0, 0));
        jButton15.setText("12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listNotifications.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        spNotifications.setViewportView(listNotifications);

        bNotificationDelete.setText("Delete");
        bNotificationDelete.setActionCommand("");
        bNotificationDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNotificationDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pNotificationsLayout = new javax.swing.GroupLayout(pNotifications);
        pNotifications.setLayout(pNotificationsLayout);
        pNotificationsLayout.setHorizontalGroup(
                pNotificationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(spNotifications)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pNotificationsLayout.createSequentialGroup()
                                .addContainerGap(356, Short.MAX_VALUE)
                                .addComponent(bNotificationDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(350, 350, 350))
        );
        pNotificationsLayout.setVerticalGroup(
                pNotificationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pNotificationsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(spNotifications, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(bNotificationDelete)
                                .addContainerGap(24, Short.MAX_VALUE))
        );

        tpFOHGUIMain.addTab("Notifications", pNotifications);

        tMenu.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Name", "Price", "Description", "Allergies"
                }
        ));
        spMenu.setViewportView(tMenu);

        javax.swing.GroupLayout pMenuLayout = new javax.swing.GroupLayout(pMenu);
        pMenu.setLayout(pMenuLayout);
        pMenuLayout.setHorizontalGroup(
                pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pMenuLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(spMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                                .addContainerGap())
        );
        pMenuLayout.setVerticalGroup(
                pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pMenuLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(spMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                                .addContainerGap())
        );

        tpFOHGUIMain.addTab("Menu", pMenu);

        pNewBooking.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "New Booking:", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        tfNbName.setDragEnabled(true);
        tfNbName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNbNameActionPerformed(evt);
            }
        });

        lNbName.setText("Name:");

        lNbPhoneNumber.setText("Phone Number:");

        tfNbPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNbPhoneNumberActionPerformed(evt);
            }
        });

        lNbNoGuests.setText("Number of Guests:");

        lNbTime.setText("Time:");

        lNbDate.setText("Date:");

        bNbSubmit.setText("SUBMIT");

        lNbTables.setText("Tables:");

        cbNbDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbNbMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbNbYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbNbHour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbNbMinute.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbNbNoGuests.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lNbBookingLength.setText("Booking Length:");

        cbNbBookingLength.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tfTables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTablesActionPerformed(evt);
            }
        });

        lNbWaiter.setText("Waiter:");

        cbNbWaiter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pNewBookingLayout = new javax.swing.GroupLayout(pNewBooking);
        pNewBooking.setLayout(pNewBookingLayout);
        pNewBookingLayout.setHorizontalGroup(
                pNewBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pNewBookingLayout.createSequentialGroup()
                                .addGap(0, 66, Short.MAX_VALUE)
                                .addGroup(pNewBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfNbName, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfNbPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(59, 59, 59))
                        .addGroup(pNewBookingLayout.createSequentialGroup()
                                .addGroup(pNewBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pNewBookingLayout.createSequentialGroup()
                                                .addGap(130, 130, 130)
                                                .addComponent(lNbName))
                                        .addGroup(pNewBookingLayout.createSequentialGroup()
                                                .addGap(101, 101, 101)
                                                .addComponent(lNbPhoneNumber))
                                        .addGroup(pNewBookingLayout.createSequentialGroup()
                                                .addGap(129, 129, 129)
                                                .addComponent(lNbDate))
                                        .addGroup(pNewBookingLayout.createSequentialGroup()
                                                .addGap(129, 129, 129)
                                                .addComponent(lNbTime, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(pNewBookingLayout.createSequentialGroup()
                                                .addGap(123, 123, 123)
                                                .addComponent(lNbTables, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(pNewBookingLayout.createSequentialGroup()
                                                .addGap(86, 86, 86)
                                                .addGroup(pNewBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(cbNbWaiter, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(bNbSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(pNewBookingLayout.createSequentialGroup()
                                                .addGap(122, 122, 122)
                                                .addComponent(lNbWaiter))
                                        .addGroup(pNewBookingLayout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addGroup(pNewBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(pNewBookingLayout.createSequentialGroup()
                                                                .addGroup(pNewBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(cbNbBookingLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(pNewBookingLayout.createSequentialGroup()
                                                                                .addGap(30, 30, 30)
                                                                                .addComponent(cbNbHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(pNewBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(pNewBookingLayout.createSequentialGroup()
                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                .addComponent(cbNbNoGuests, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(pNewBookingLayout.createSequentialGroup()
                                                                                .addComponent(cbNbMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(0, 0, Short.MAX_VALUE))))
                                                        .addGroup(pNewBookingLayout.createSequentialGroup()
                                                                .addComponent(lNbBookingLength)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(lNbNoGuests))
                                                        .addGroup(pNewBookingLayout.createSequentialGroup()
                                                                .addComponent(cbNbDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(cbNbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(cbNbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pNewBookingLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(tfTables, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pNewBookingLayout.setVerticalGroup(
                pNewBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pNewBookingLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lNbName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNbName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lNbPhoneNumber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNbPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lNbDate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pNewBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cbNbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbNbDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbNbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lNbTime)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pNewBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cbNbHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbNbMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pNewBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lNbBookingLength)
                                        .addComponent(lNbNoGuests))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pNewBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cbNbBookingLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbNbNoGuests, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lNbTables)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfTables, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lNbWaiter)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbNbWaiter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(bNbSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(11, Short.MAX_VALUE))
        );

        pEditBooking.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edit Booking:", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        bBookingDelete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bBookingDelete.setText("DELETE");
        bBookingDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBookingDeleteActionPerformed(evt);
            }
        });

        tBookings.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null}
                },
                new String [] {
                        "Name", "Phone No", "No. Guests", "Time", "Date", "Table"
                }
        ));
        spEditBooking.setViewportView(tBookings);

        cbBookingsSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tonights Bookings", "All Bookings" }));

        bBookingEdit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bBookingEdit.setText("EDIT");

        javax.swing.GroupLayout pEditBookingLayout = new javax.swing.GroupLayout(pEditBooking);
        pEditBooking.setLayout(pEditBookingLayout);
        pEditBookingLayout.setHorizontalGroup(
                pEditBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(spEditBooking, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pEditBookingLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbBookingsSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(163, 163, 163))
                        .addGroup(pEditBookingLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(bBookingDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bBookingEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73))
        );
        pEditBookingLayout.setVerticalGroup(
                pEditBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pEditBookingLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(cbBookingsSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spEditBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(pEditBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(bBookingDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                                        .addComponent(bBookingEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pBookingLayout = new javax.swing.GroupLayout(pBooking);
        pBooking.setLayout(pBookingLayout);
        pBookingLayout.setHorizontalGroup(
                pBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pBookingLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pNewBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pEditBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        pBookingLayout.setVerticalGroup(
                pBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pBookingLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(pEditBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pNewBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );

        tpFOHGUIMain.addTab("Booking", pBooking);

        listUnpaidOrders.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Table 1", "Table 2", "Table3" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        spUnpaidOrders.setViewportView(listUnpaidOrders);

        lUnpaidOrders.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lUnpaidOrders.setText("Unpaid Orders:");

        bPrintBill.setText("Print Bill");
        bPrintBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPrintBillActionPerformed(evt);
            }
        });

        bEditBill.setText("Edit Bill");
        bEditBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditBillActionPerformed(evt);
            }
        });

        listSelectedBill.setColumns(20);
        listSelectedBill.setRows(5);
        spSelectedBill.setViewportView(listSelectedBill);

        lSelectedBill.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lSelectedBill.setText("Selected Bill:");

        bBillHistory.setText("Bill History");

        bSplitBill.setText("Split Bill");

        javax.swing.GroupLayout pPaymentLayout = new javax.swing.GroupLayout(pPayment);
        pPayment.setLayout(pPaymentLayout);
        pPaymentLayout.setHorizontalGroup(
                pPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pPaymentLayout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(lUnpaidOrders)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lSelectedBill)
                                .addGap(129, 129, 129))
                        .addGroup(pPaymentLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(spUnpaidOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addGroup(pPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(bBillHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bSplitBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bPrintBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bEditBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                .addComponent(spSelectedBill, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        pPaymentLayout.setVerticalGroup(
                pPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pPaymentLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(pPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lUnpaidOrders, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lSelectedBill, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(pPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pPaymentLayout.createSequentialGroup()
                                                .addGap(100, 100, 100)
                                                .addComponent(bEditBill)
                                                .addGap(43, 43, 43)
                                                .addComponent(bPrintBill)
                                                .addGap(46, 46, 46)
                                                .addComponent(bSplitBill)
                                                .addGap(45, 45, 45)
                                                .addComponent(bBillHistory)
                                                .addGap(0, 95, Short.MAX_VALUE))
                                        .addGroup(pPaymentLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(pPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(spSelectedBill)
                                                        .addComponent(spUnpaidOrders))))
                                .addContainerGap())
        );

        tpFOHGUIMain.addTab("Payment", pPayment);

        lOrders.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lOrders.setText("Orders:");

        bOEdit.setText("Edit");
        bOEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOEditActionPerformed(evt);
            }
        });

        bODelete.setText("Delete");

        bOArchive.setText("Archive");

        bONewOrder.setText("New Order");
        bONewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bONewOrderActionPerformed(evt);
            }
        });

        tOrders.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        spOrders.setViewportView(tOrders);

        javax.swing.GroupLayout pOrderLayout = new javax.swing.GroupLayout(pOrder);
        pOrder.setLayout(pOrderLayout);
        pOrderLayout.setHorizontalGroup(
                pOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pOrderLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addGap(107, 107, 107))
                        .addGroup(pOrderLayout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(bOEdit)
                                .addGap(97, 97, 97)
                                .addComponent(bODelete)
                                .addGap(102, 102, 102)
                                .addComponent(bOArchive)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bONewOrder)
                                .addGap(97, 97, 97))
                        .addGroup(pOrderLayout.createSequentialGroup()
                                .addGroup(pOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pOrderLayout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addComponent(spOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(pOrderLayout.createSequentialGroup()
                                                .addGap(346, 346, 346)
                                                .addComponent(lOrders)))
                                .addContainerGap(35, Short.MAX_VALUE))
        );
        pOrderLayout.setVerticalGroup(
                pOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pOrderLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lOrders)
                                .addGap(18, 18, 18)
                                .addComponent(spOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addGroup(pOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bOEdit)
                                        .addComponent(bODelete)
                                        .addComponent(bOArchive)
                                        .addComponent(bONewOrder))
                                .addContainerGap(22, Short.MAX_VALUE))
        );

        tpFOHGUIMain.addTab("Order", pOrder);

        pTablePlan.setLayout(null);

        bTable9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bTable9.setText("9");
        pTablePlan.add(bTable9);
        bTable9.setBounds(278, 186, 112, 64);

        bTable13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bTable13.setText("13");
        pTablePlan.add(bTable13);
        bTable13.setBounds(18, 330, 112, 62);

        bTable1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bTable1.setText("1");
        pTablePlan.add(bTable1);
        bTable1.setBounds(18, 34, 112, 68);

        bTable6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bTable6.setText("6");
        pTablePlan.add(bTable6);
        bTable6.setBounds(668, 36, 112, 66);

        bTable15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bTable15.setText("15");
        pTablePlan.add(bTable15);
        bTable15.setBounds(278, 328, 112, 64);

        bTable14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bTable14.setText("14");
        pTablePlan.add(bTable14);
        bTable14.setBounds(148, 330, 112, 62);

        bTable5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bTable5.setText("5");
        pTablePlan.add(bTable5);
        bTable5.setBounds(538, 36, 112, 66);

        bTable2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bTable2.setText("2");
        pTablePlan.add(bTable2);
        bTable2.setBounds(148, 34, 112, 68);

        bTable4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bTable4.setText("4");
        pTablePlan.add(bTable4);
        bTable4.setBounds(408, 36, 112, 66);

        bTable12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bTable12.setText("12");
        pTablePlan.add(bTable12);
        bTable12.setBounds(668, 186, 112, 64);

        bTable8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bTable8.setText("8");
        pTablePlan.add(bTable8);
        bTable8.setBounds(148, 186, 112, 64);

        bTable10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bTable10.setText("10");
        pTablePlan.add(bTable10);
        bTable10.setBounds(408, 186, 112, 64);

        bTable11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bTable11.setText("11");
        pTablePlan.add(bTable11);
        bTable11.setBounds(538, 186, 112, 64);

        bTable3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bTable3.setText("3");
        pTablePlan.add(bTable3);
        bTable3.setBounds(278, 34, 112, 68);

        bTable7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bTable7.setText("7");
        pTablePlan.add(bTable7);
        bTable7.setBounds(18, 186, 112, 64);

        cbTpDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Date", "21/03/2024", "22/03/2024", "23/03/2024", "24/03/2024", "25/03/2024" }));
        pTablePlan.add(cbTpDay);
        cbTpDay.setBounds(620, 310, 70, 22);

        cbTpYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Time", "12:00", "12:30", "13:00", "13:30" }));
        pTablePlan.add(cbTpYear);
        cbTpYear.setBounds(436, 310, 72, 22);

        tbTp1S.setText("S");
        pTablePlan.add(tbTp1S);
        tbTp1S.setBounds(20, 108, 36, 23);

        tbTp1M.setText("M");
        pTablePlan.add(tbTp1M);
        tbTp1M.setBounds(56, 108, 38, 23);

        tbTp1D.setText("D");
        pTablePlan.add(tbTp1D);
        tbTp1D.setBounds(94, 108, 38, 23);

        tbTp2S.setText("S");
        pTablePlan.add(tbTp2S);
        tbTp2S.setBounds(150, 108, 38, 23);

        tbTp2M.setText("M");
        pTablePlan.add(tbTp2M);
        tbTp2M.setBounds(188, 108, 38, 23);

        tbTp2D.setText("D");
        pTablePlan.add(tbTp2D);
        tbTp2D.setBounds(226, 108, 38, 23);

        tbTp3S.setText("S");
        pTablePlan.add(tbTp3S);
        tbTp3S.setBounds(280, 108, 38, 23);

        tbTp3M.setText("M");
        tbTp3M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTp3MActionPerformed(evt);
            }
        });
        pTablePlan.add(tbTp3M);
        tbTp3M.setBounds(316, 108, 38, 23);

        tbTp3D.setText("D");
        pTablePlan.add(tbTp3D);
        tbTp3D.setBounds(354, 108, 38, 23);

        tbTp4S.setText("S");
        pTablePlan.add(tbTp4S);
        tbTp4S.setBounds(410, 108, 38, 23);

        tbTp4M.setText("M");
        pTablePlan.add(tbTp4M);
        tbTp4M.setBounds(446, 108, 38, 23);

        tbTp4D.setText("D");
        pTablePlan.add(tbTp4D);
        tbTp4D.setBounds(482, 108, 38, 23);

        tbTp5S.setText("S");
        pTablePlan.add(tbTp5S);
        tbTp5S.setBounds(542, 108, 38, 23);

        tbTp5M.setText("M");
        pTablePlan.add(tbTp5M);
        tbTp5M.setBounds(580, 108, 38, 23);

        tbTp5D.setText("D");
        pTablePlan.add(tbTp5D);
        tbTp5D.setBounds(616, 108, 38, 23);

        tbTp6S.setText("S");
        pTablePlan.add(tbTp6S);
        tbTp6S.setBounds(672, 108, 38, 23);

        tbTp6M.setText("M");
        pTablePlan.add(tbTp6M);
        tbTp6M.setBounds(710, 108, 38, 23);

        tbTp6D.setText("D");
        pTablePlan.add(tbTp6D);
        tbTp6D.setBounds(746, 108, 38, 23);

        tbTp7S.setText("S");
        pTablePlan.add(tbTp7S);
        tbTp7S.setBounds(20, 256, 38, 23);

        tbTp7M.setText("M");
        tbTp7M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTp7MActionPerformed(evt);
            }
        });
        pTablePlan.add(tbTp7M);
        tbTp7M.setBounds(56, 256, 38, 23);

        tbTp7D.setText("D");
        tbTp7D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTp7DActionPerformed(evt);
            }
        });
        pTablePlan.add(tbTp7D);
        tbTp7D.setBounds(92, 256, 38, 23);

        tbTp13S.setText("S");
        pTablePlan.add(tbTp13S);
        tbTp13S.setBounds(20, 398, 38, 23);

        tbTp13M.setText("M");
        pTablePlan.add(tbTp13M);
        tbTp13M.setBounds(56, 398, 38, 23);

        tbTp13D.setText("D");
        pTablePlan.add(tbTp13D);
        tbTp13D.setBounds(92, 398, 38, 23);

        tbTp14S.setText("S");
        pTablePlan.add(tbTp14S);
        tbTp14S.setBounds(150, 398, 38, 23);

        tbTp14M.setText("M");
        tbTp14M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTp14MActionPerformed(evt);
            }
        });
        pTablePlan.add(tbTp14M);
        tbTp14M.setBounds(186, 398, 38, 23);

        tbTp14D.setText("D");
        pTablePlan.add(tbTp14D);
        tbTp14D.setBounds(222, 398, 38, 23);

        tbTp15S.setText("S");
        pTablePlan.add(tbTp15S);
        tbTp15S.setBounds(280, 398, 38, 23);

        tbTp15M.setText("M");
        pTablePlan.add(tbTp15M);
        tbTp15M.setBounds(316, 398, 38, 23);

        tbTp15D.setText("D");
        pTablePlan.add(tbTp15D);
        tbTp15D.setBounds(352, 398, 38, 23);

        tbTp8S.setText("S");
        pTablePlan.add(tbTp8S);
        tbTp8S.setBounds(148, 258, 38, 23);

        tbTp8M.setText("M");
        pTablePlan.add(tbTp8M);
        tbTp8M.setBounds(186, 258, 38, 23);

        tbTp8D.setText("D");
        pTablePlan.add(tbTp8D);
        tbTp8D.setBounds(222, 258, 38, 23);

        tbTp9S.setText("S");
        pTablePlan.add(tbTp9S);
        tbTp9S.setBounds(280, 258, 38, 23);

        tbTp9M.setText("M");
        pTablePlan.add(tbTp9M);
        tbTp9M.setBounds(318, 258, 38, 23);

        tbTp9D.setText("D");
        pTablePlan.add(tbTp9D);
        tbTp9D.setBounds(354, 258, 38, 23);

        tbTp10S.setText("S");
        pTablePlan.add(tbTp10S);
        tbTp10S.setBounds(410, 258, 38, 23);

        tbTp10M.setText("M");
        pTablePlan.add(tbTp10M);
        tbTp10M.setBounds(446, 258, 38, 23);

        tbTp10D.setText("D");
        pTablePlan.add(tbTp10D);
        tbTp10D.setBounds(484, 258, 38, 23);

        tbTp11S.setText("S");
        pTablePlan.add(tbTp11S);
        tbTp11S.setBounds(540, 258, 38, 23);

        tbTp11M.setText("M");
        pTablePlan.add(tbTp11M);
        tbTp11M.setBounds(576, 258, 38, 23);

        tbTp11D.setText("D");
        pTablePlan.add(tbTp11D);
        tbTp11D.setBounds(612, 258, 38, 23);

        tbTp12S.setText("S");
        pTablePlan.add(tbTp12S);
        tbTp12S.setBounds(670, 256, 38, 23);

        tbTp12M.setText("M");
        pTablePlan.add(tbTp12M);
        tbTp12M.setBounds(708, 256, 38, 23);

        tbTp12D.setText("D");
        pTablePlan.add(tbTp12D);
        tbTp12D.setBounds(744, 256, 38, 23);

        cbTpMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pTablePlan.add(cbTpMonth);
        cbTpMonth.setBounds(530, 310, 72, 22);

        cbTpHour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Date", "21/03/2024", "22/03/2024", "23/03/2024", "24/03/2024", "25/03/2024" }));
        pTablePlan.add(cbTpHour);
        cbTpHour.setBounds(486, 352, 70, 22);

        cbTpMinutes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Date", "21/03/2024", "22/03/2024", "23/03/2024", "24/03/2024", "25/03/2024" }));
        pTablePlan.add(cbTpMinutes);
        cbTpMinutes.setBounds(578, 352, 70, 22);

        lTp15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lTp15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTp15.setText("wiater");
        pTablePlan.add(lTp15);
        lTp15.setBounds(292, 308, 86, 16);

        lTp1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lTp1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTp1.setText("wiater");
        pTablePlan.add(lTp1);
        lTp1.setBounds(30, 14, 86, 20);

        lTp2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lTp2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTp2.setText("wiater");
        pTablePlan.add(lTp2);
        lTp2.setBounds(162, 14, 86, 16);

        lTp3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lTp3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTp3.setText("wiater");
        pTablePlan.add(lTp3);
        lTp3.setBounds(292, 14, 86, 16);

        lTp4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lTp4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTp4.setText("wiater");
        pTablePlan.add(lTp4);
        lTp4.setBounds(418, 16, 86, 16);

        lTp5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lTp5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTp5.setText("wiater");
        pTablePlan.add(lTp5);
        lTp5.setBounds(550, 16, 86, 16);

        lTp6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lTp6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTp6.setText("wiater");
        pTablePlan.add(lTp6);
        lTp6.setBounds(682, 16, 86, 16);

        lTp7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lTp7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTp7.setText("wiater");
        pTablePlan.add(lTp7);
        lTp7.setBounds(32, 164, 86, 16);

        lTp8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lTp8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTp8.setText("wiater");
        pTablePlan.add(lTp8);
        lTp8.setBounds(162, 166, 86, 16);

        lTp9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lTp9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTp9.setText("wiater");
        pTablePlan.add(lTp9);
        lTp9.setBounds(292, 166, 86, 16);

        lTp10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lTp10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTp10.setText("wiater");
        pTablePlan.add(lTp10);
        lTp10.setBounds(422, 166, 86, 16);

        lTp11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lTp11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTp11.setText("wiater");
        pTablePlan.add(lTp11);
        lTp11.setBounds(550, 166, 86, 16);

        lTp12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lTp12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTp12.setText("wiater");
        pTablePlan.add(lTp12);
        lTp12.setBounds(682, 166, 86, 16);

        lTp13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lTp13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTp13.setText("wiater");
        pTablePlan.add(lTp13);
        lTp13.setBounds(32, 310, 86, 16);

        lTp14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lTp14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTp14.setText("wiater");
        pTablePlan.add(lTp14);
        lTp14.setBounds(162, 310, 86, 16);

        tpFOHGUIMain.addTab("Table Plan", pTablePlan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tpFOHGUIMain, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tpFOHGUIMain)
        );

        pack();
    }// </editor-fold>

    private void bNotificationDeleteActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void bBookingDeleteActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void tfNbNameActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void tfNbPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void bPrintBillActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void bEditBillActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void bOEditActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void bONewOrderActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        NewOrder order = new NewOrder();
        order.setVisible(true);
    }

    private void tfTablesActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void tbTp3MActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void tbTp7MActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void tbTp14MActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void tbTp7DActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabbedGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabbedGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabbedGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabbedGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabbedGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton bBillHistory;
    private javax.swing.JButton bBookingDelete;
    private javax.swing.JButton bBookingEdit;
    private javax.swing.JButton bEditBill;
    private javax.swing.JButton bNbSubmit;
    private javax.swing.JButton bNotificationDelete;
    private javax.swing.JButton bOArchive;
    private javax.swing.JButton bODelete;
    private javax.swing.JButton bOEdit;
    private javax.swing.JButton bONewOrder;
    private javax.swing.JButton bPrintBill;
    private javax.swing.JButton bSplitBill;
    private javax.swing.JButton bTable1;
    private javax.swing.JButton bTable10;
    private javax.swing.JButton bTable11;
    private javax.swing.JButton bTable12;
    private javax.swing.JButton bTable13;
    private javax.swing.JButton bTable14;
    private javax.swing.JButton bTable15;
    private javax.swing.JButton bTable2;
    private javax.swing.JButton bTable3;
    private javax.swing.JButton bTable4;
    private javax.swing.JButton bTable5;
    private javax.swing.JButton bTable6;
    private javax.swing.JButton bTable7;
    private javax.swing.JButton bTable8;
    private javax.swing.JButton bTable9;
    private javax.swing.JComboBox<String> cbBookingsSelect;
    private javax.swing.JComboBox<String> cbNbBookingLength;
    private javax.swing.JComboBox<String> cbNbDay;
    private javax.swing.JComboBox<String> cbNbHour;
    private javax.swing.JComboBox<String> cbNbMinute;
    private javax.swing.JComboBox<String> cbNbMonth;
    private javax.swing.JComboBox<String> cbNbNoGuests;
    private javax.swing.JComboBox<String> cbNbWaiter;
    private javax.swing.JComboBox<String> cbNbYear;
    private javax.swing.JComboBox<String> cbTpDay;
    private javax.swing.JComboBox<String> cbTpHour;
    private javax.swing.JComboBox<String> cbTpMinutes;
    private javax.swing.JComboBox<String> cbTpMonth;
    private javax.swing.JComboBox<String> cbTpYear;
    private javax.swing.JButton jButton15;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lNbBookingLength;
    private javax.swing.JLabel lNbDate;
    private javax.swing.JLabel lNbName;
    private javax.swing.JLabel lNbNoGuests;
    private javax.swing.JLabel lNbPhoneNumber;
    private javax.swing.JLabel lNbTables;
    private javax.swing.JLabel lNbTime;
    private javax.swing.JLabel lNbWaiter;
    private javax.swing.JLabel lOrders;
    private javax.swing.JLabel lSelectedBill;
    private javax.swing.JLabel lTp1;
    private javax.swing.JLabel lTp10;
    private javax.swing.JLabel lTp11;
    private javax.swing.JLabel lTp12;
    private javax.swing.JLabel lTp13;
    private javax.swing.JLabel lTp14;
    private javax.swing.JLabel lTp15;
    private javax.swing.JLabel lTp2;
    private javax.swing.JLabel lTp3;
    private javax.swing.JLabel lTp4;
    private javax.swing.JLabel lTp5;
    private javax.swing.JLabel lTp6;
    private javax.swing.JLabel lTp7;
    private javax.swing.JLabel lTp8;
    private javax.swing.JLabel lTp9;
    private javax.swing.JLabel lUnpaidOrders;
    private javax.swing.JList<String> listNotifications;
    private javax.swing.JTextArea listSelectedBill;
    private javax.swing.JList<String> listUnpaidOrders;
    private javax.swing.JPanel pBooking;
    private javax.swing.JPanel pEditBooking;
    private javax.swing.JPanel pMenu;
    private javax.swing.JPanel pNewBooking;
    private javax.swing.JPanel pNotifications;
    private javax.swing.JPanel pOrder;
    private javax.swing.JPanel pPayment;
    private javax.swing.JPanel pTablePlan;
    private javax.swing.JScrollPane spEditBooking;
    private javax.swing.JScrollPane spMenu;
    private javax.swing.JScrollPane spNotifications;
    private javax.swing.JScrollPane spOrders;
    private javax.swing.JScrollPane spSelectedBill;
    private javax.swing.JScrollPane spUnpaidOrders;
    private javax.swing.JTable tBookings;
    private javax.swing.JTable tMenu;
    private javax.swing.JTable tOrders;
    private javax.swing.JToggleButton tbTp10D;
    private javax.swing.JToggleButton tbTp10M;
    private javax.swing.JToggleButton tbTp10S;
    private javax.swing.JToggleButton tbTp11D;
    private javax.swing.JToggleButton tbTp11M;
    private javax.swing.JToggleButton tbTp11S;
    private javax.swing.JToggleButton tbTp12D;
    private javax.swing.JToggleButton tbTp12M;
    private javax.swing.JToggleButton tbTp12S;
    private javax.swing.JToggleButton tbTp13D;
    private javax.swing.JToggleButton tbTp13M;
    private javax.swing.JToggleButton tbTp13S;
    private javax.swing.JToggleButton tbTp14D;
    private javax.swing.JToggleButton tbTp14M;
    private javax.swing.JToggleButton tbTp14S;
    private javax.swing.JToggleButton tbTp15D;
    private javax.swing.JToggleButton tbTp15M;
    private javax.swing.JToggleButton tbTp15S;
    private javax.swing.JToggleButton tbTp1D;
    private javax.swing.JToggleButton tbTp1M;
    private javax.swing.JToggleButton tbTp1S;
    private javax.swing.JToggleButton tbTp2D;
    private javax.swing.JToggleButton tbTp2M;
    private javax.swing.JToggleButton tbTp2S;
    private javax.swing.JToggleButton tbTp3D;
    private javax.swing.JToggleButton tbTp3M;
    private javax.swing.JToggleButton tbTp3S;
    private javax.swing.JToggleButton tbTp4D;
    private javax.swing.JToggleButton tbTp4M;
    private javax.swing.JToggleButton tbTp4S;
    private javax.swing.JToggleButton tbTp5D;
    private javax.swing.JToggleButton tbTp5M;
    private javax.swing.JToggleButton tbTp5S;
    private javax.swing.JToggleButton tbTp6D;
    private javax.swing.JToggleButton tbTp6M;
    private javax.swing.JToggleButton tbTp6S;
    private javax.swing.JToggleButton tbTp7D;
    private javax.swing.JToggleButton tbTp7M;
    private javax.swing.JToggleButton tbTp7S;
    private javax.swing.JToggleButton tbTp8D;
    private javax.swing.JToggleButton tbTp8M;
    private javax.swing.JToggleButton tbTp8S;
    private javax.swing.JToggleButton tbTp9D;
    private javax.swing.JToggleButton tbTp9M;
    private javax.swing.JToggleButton tbTp9S;
    private javax.swing.JTextField tfNbName;
    private javax.swing.JTextField tfNbPhoneNumber;
    private javax.swing.JTextField tfTables;
    private javax.swing.JTabbedPane tpFOHGUIMain;
    // End of variables declaration
}
